### ISSUE TITLE
I am using ubuntu, when I use ./bypass it tells me it cannot find ./ bypass

### ISSUE THREAD

**Issue by tomsarra** [AwesomeKids652/icloud_bypass#1]
I am opening terminal  in folder that downloaded program is located in.
What am I doing wrong?
Thanks 
Tom S

**Comment by AwesomeKids652** [comment]
I Am very much sorry for a late response! did you do a compile? or download a release?
what did you do in total?

**Comment by AwesomeKids652** [comment]
did u try ./bypassr 
in the current folder?

**Comment by AwesomeKids652** [comment]
you have followed a LOT wrong! download the latest release, place it in anywhere, go into the folder you downloaded the release,

**Comment by AwesomeKids652** [comment]
run ./bypassr

**Comment by tomsarra** [comment]
Hi thanks, response was just fine, sorry for the messy messages.
I am using ubuntu 21.04, I cloned the program, cd , opened terminal in that folder then did ./bypass.
Am I to run autogen.sh?
Again thanks
Tom S

**Comment by tomsarra** [comment]
One more question, does my iPad need to be jailbroke for this to work?
Tom S

**Comment by AwesomeKids652** [comment]
Yes!
Remember, it only works under 12.0.0.
or else your home button will FAIL to work.
