### ISSUE TITLE
does it work with a12&13 chip iPhones?

### ISSUE THREAD

**Issue by itsbek** [AwesomeKids652/icloud_bypass#3]
Hey there, was wondering if your code works with new gen iDevices(XS, XS Max, 11 Pro/Pro Max)?

**Comment by AwesomeKids652** [comment]
i guess so. 
it seems to work out for me.
just not on the 12/13 im making a bypass for that

**Comment by AwesomeKids652** [comment]
Hey back here again!

it looks like it doesnt work anymore.
Sorry for the inconvenience!
